// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJlmd9tXpJqXEYCSesLt8AjmaQ_psam4s',
    appId: '1:444548366516:web:e55371dbc418f39d0417e1',
    messagingSenderId: '444548366516',
    projectId: 'flutter-fitness-app-fc730',
    authDomain: 'flutter-fitness-app-fc730.firebaseapp.com',
    storageBucket: 'flutter-fitness-app-fc730.firebasestorage.app',
    measurementId: 'G-CNYVPVZTMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6YOtCSPLGPFtonUO8LQn0jXXc_xSogCI',
    appId: '1:444548366516:android:5a5da6e98898856c0417e1',
    messagingSenderId: '444548366516',
    projectId: 'flutter-fitness-app-fc730',
    storageBucket: 'flutter-fitness-app-fc730.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0qttUQoXjYmNYePCIRPf9uBSpB2g0U34',
    appId: '1:444548366516:ios:17ef278bb86364bf0417e1',
    messagingSenderId: '444548366516',
    projectId: 'flutter-fitness-app-fc730',
    storageBucket: 'flutter-fitness-app-fc730.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0qttUQoXjYmNYePCIRPf9uBSpB2g0U34',
    appId: '1:444548366516:ios:17ef278bb86364bf0417e1',
    messagingSenderId: '444548366516',
    projectId: 'flutter-fitness-app-fc730',
    storageBucket: 'flutter-fitness-app-fc730.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJlmd9tXpJqXEYCSesLt8AjmaQ_psam4s',
    appId: '1:444548366516:web:d1e684b1544785430417e1',
    messagingSenderId: '444548366516',
    projectId: 'flutter-fitness-app-fc730',
    authDomain: 'flutter-fitness-app-fc730.firebaseapp.com',
    storageBucket: 'flutter-fitness-app-fc730.firebasestorage.app',
    measurementId: 'G-34JQRP15PB',
  );
}
